### ISSUE TITLE
When is the paper going to be published?

### ISSUE THREAD

**Issue by yogeshchandrasekharuni** [amazon-science/pizza-semantic-parsing-dataset#2]
Hi, (when) is the paper for this dataset going to be published? TIA.

**Comment by mesnarn** [comment]
We are in the process to release the paper on arxiv, and expect it to be completed within the next 4 weeks.

**Comment by mesnarn** [comment]
Paper is released on arxiv https://arxiv.org/abs/2212.00265 

Bibtex will be updated in following days

**Comment by yogeshchandrasekharuni** [comment]
Thank you and congratulations!!
